### ISSUE TITLE
REMINDER: The branch used on Minor Name Change testing server is not the main branch, but is instead the work_in_progress_parent_guardian_assent_changes branch

### ISSUE THREAD

**Issue by rditcham** [SuffolkLITLab/docassemble-PetitionToChangeNameMinorCJP25#129]
In the future, when addressing how the assent questions are asked for parents and guardians, you may need to switch back to the main branch. The main branch is at the stage where assent is only asked of those who have said that they are presenting the form on behalf of the child. Each of the changes made to the work in progress branch are detailed in the prior GitHub Issue.

**Comment by nonprofittechy** [comment]
This issue appears stale--all of the work is merged
